name: Eighth GitHub Actions Workflow

on: 
  workflow_dispatch:
    inputs:
      example-title:
        description: Type your title here
        required: false
        type: string
        default: default value

jobs:
  display-node-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Display the NodeJS and npm versions on Ubuntu
        run: |
          node -v
          npm -v
