name: Eighth GitHub Actions Workflow

on: 
  workflow_dispatch:
    inputs:
      exampleTitle:
        description: Type your title here
        required: true
        type: string
        default: default value
      exampleChoice:
        description: 'Select on of the options'
        required: true
        default: 'Value 1'
        type: choice
        options:
          - Value 0
          - Value 1
          - Value 2
          - Value 3

jobs:
  display-node-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Display the NodeJS and npm versions on Ubuntu
        run: |
          node -v
          npm -v
          echo "Title is: ${{ inputs.exampleTitle }}"
