name: Fifteenth GitHub Actions Workflow

on: push

run-name: GitHub Actions Artifacts

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Math expression
        run: expr 2 + 2 >> math-result.txt

      - name: Upload result file
        uses: actions/upload-artifact@v6
        with:
          name: math-result
          path: math-result.txt

  another-job:
    runs-on: ubuntu-latest
    needs: first-job
    steps:
      - name: Download result file
        uses: actions/download-artifact@v6
        with:
          name: math-result

      - name: Math expression
        run: |
          value=`cat math-result.txt`
          echo "Previous value: $value"
          expr $value \* 2 >> math-result.txt

      - name: Upload result file
        uses: actions/upload-artifact@v6
        with:
          name: math-result
          path: math-result.txt

  second-job:
    runs-on: ubuntu-latest
    needs: another-job
    steps:
      - name: Download result file
        uses: actions/download-artifact@v6
        with:
          name: math-result

      - name: Display filex
        run: ls -la

      - name: Display result
        run: |
          value=`cat math-result.txt`
          echo $value
