name: Fifth GitHub Actions Workflow

on: 
  issues:
    types: [edited, closed]
  pull_request:
    types: [assigned, closed]

jobs:
    first-command:
        runs-on: ubuntu-latest
        steps:
            - name: Display message for push or issues event
              run: |
                echo "This is the fiveth GitHub Actions workflow triggered by a ${{ github.event_name }} event."
                echo $GITHUB_SHA
                echo $GITHUB_REF