name: First GitHub Actions Workflow

on: [push]

jobs:
    run-first-command:
        runs-on: ubuntu-latest
        steps:
            - name: Display some text
              run: echo "Hello, World! Text from the first GitHub Actions workflow."
            - name: List files in the repository
              run: ls -la