name: First GitHub Actions Workflow

# on: [push]
on: workflow_dispatch

jobs:
    run-first-command:
        runs-on: ubuntu-latest
        steps:
            - name: Display some text
              run: echo "Hello, World! Text from the first GitHub Actions workflow."
            - name: List files in the repository
              run: ls -la
            - name: Display the current NodeJS and npm versions
              run: |
                node -v
                npm -v