name: Fourth GitHub Actions Workflow


on: 
    workflow_run:
        workflows: 
            - Third GitHub Actions Workflow
        types:
            - completed

jobs:
    success-command:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        steps:
            - name: Display message "Hello"
              run: echo "Success Hello"

    failure-command:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        steps:
            - name: Display message "Goodbye"
              run: echo "Failure Goodbye"