name: Sixteenth GitHub Actions Workflow

on: push

run-name: GitHub Actions Matrix

jobs:
  first-job:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [14, 16, 18]
        include:
          - os: macos-latest
            node-version: 20
        exclude:
          - os: windows-latest
            node-version: 14
          - os: windows-latest
            node-version: 16
      fail-fast: false
    runs-on: ${{ matrix.os}}
    steps:
      - name: Display NodeJS version before setup
        run: node -v

      - name: Setup NodeJS
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}

      - name: Display NodeJS version after setup
        run: node -v
