name: Sixth GitHub Actions Workflow

on:
  push:
    branches:
      - main
      - pages/*
    # tags:
    #   - v1.*
    #   - "!v1.2.1"
    paths:
      - "**.html"

jobs:
  command-first:
    runs-on: ubuntu-latest
    steps:
      - name: Show Ubuntu version
        run: lsb_release -a
