name: Third GitHub Actions Workflow

on: push

jobs:
    run-first-command:
        runs-on: ubuntu-latest
        steps:
            - name: List files in the current directory and copy repository
              run: ls -a
            - uses: actions/checkout@v6
            - name: List files after checkout
              run: ls -a