name: Third GitHub Actions Workflow

on: push

jobs:
    run-first-command:
        runs-on: ubuntu-latest
        steps:
            - name: List files in the current directory before copy
              run: lsds -a
            # - uses: actions/checkout@v6
            - name: Copy files
              run: |
                git config --global init.defaultBranch main
                git init
                git remote add origin "https://$GITHUB_ACTOR:${{secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"                
                git fetch origin
                git checkout main
            - name: List files in the current directory after copy
              run: ls -a