name: Third GitHub Actions Workflow

on: push

jobs:
    run-first-command:
        runs-on: ubuntu-latest
        steps:
            - name: Display the Python version on Ubuntu
              run: python3 --version