name: Third GitHub Actions Workflow

on: push

jobs:
    run-first-command:
        runs-on: ubuntu-latest
        steps:
            - name: List files in the current directory and the current directory path
              run: |
                pwd
                ls -a